services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - redis

    networks:
      - default-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379

    networks:
      - default-network

networks:
  default-network:
